api:
  omdb: http://www.omdbapi.com/?apikey=${API_KEY}
spring:
  r2dbc:
    username: furious
    password: furious
    url: r2dbc:postgresql://localhost:5432/furious
  flyway:
    url: jdbc:postgresql://localhost:5432/furious
    user: furious
    password: furious
    baseline-on-migrate: true
server:
  port: 8081
